spring:
  application:
    name: NotebookClient

server:
  port: 60022


eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.177.79:8080/eureka/v2/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 0
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false